### ISSUE TITLE
Unsupported GOARCH: arm64

### ISSUE THREAD

**Issue by alejandro-a** [hajimehoshi/go-inovation#13]
I tried to build this project on linux/arm64 and this error occurs. I used the following command:
`go run github.com/hajimehoshi/ebiten/v2/cmd/ebitenmobile bind -target android -androidapi 34 -javapkg com.hajimehoshi.goinovation -o ./mobile/android/inovation/inovation.aar ./mobile`

And produce the following error:

```
panic: unsupported GOARCH: arm64
goroutine 1 [running]:
main.archNDK(...)
        /home/byteborne/go/1.21.1/pkg/mod/golang.org/x/mobile@v0.0.0-20230906021930-dc64209e86f1/cmd/gomobile/env.go:535
main.(*ndkToolchain).Path.func1({0x4000162240, 0x1a})
        /home/byteborne/go/1.21.1/pkg/mod/golang.org/x/mobile@v0.0.0-20230906021930-dc64209e86f1/cmd/gomobile/env.go:558 +0x170
main.(*ndkToolchain).Path(0x0?, {0x40000280d1?, 0x0?}, {0x3a9678?, 0x78696e6f72646e61?})
        /home/byteborne/go/1.21.1/pkg/mod/golang.org/x/mobile@v0.0.0-20230906021930-dc64209e86f1/cmd/gomobile/env.go:564 +0xbc
main.envInit()
        /home/byteborne/go/1.21.1/pkg/mod/golang.org/x/mobile@v0.0.0-20230906021930-dc64209e86f1/cmd/gomobile/env.go:165 +0x170
main.buildEnvInit()
        /home/byteborne/go/1.21.1/pkg/mod/golang.org/x/mobile@v0.0.0-20230906021930-dc64209e86f1/cmd/gomobile/env.go:150 +0x2a4
main.runBind(0x6905a0)
        /home/byteborne/go/1.21.1/pkg/mod/golang.org/x/mobile@v0.0.0-20230906021930-dc64209e86f1/cmd/gomobile/bind.go:74 +0x34
main.main()
        /home/byteborne/go/1.21.1/pkg/mod/golang.org/x/mobile@v0.0.0-20230906021930-dc64209e86f1/cmd/gomobile/main.go:74 +0x3d0
exit status 2
```

Can someone help me to compile it on linux?

**Comment by hajimehoshi** [comment]
Does this work without `-androidapi 34`?

**Comment by hajimehoshi** [comment]
Apparently GOOS=linux / GOARCH=arm64 doesn't work with gomobile unfortunately...

* https://github.com/golang/mobile/blob/e2f452493d570cfe278e63eccec99e62d4c775e5/cmd/gomobile/env.go#L515
* https://github.com/golang/go/issues/48510
