### ISSUE TITLE
Crash on Windows

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/go-inovation#3]
```
fatal error: concurrent map writes                                                                                                                                    

goroutine 10 [running]:                                                                                                                                               
runtime.throw(0x6fc320, 0x15)                                                                                                                                         
        C:/Go/src/runtime/panic.go:530 +0x97 fp=0xc082119dc0 sp=0xc082119da8                                                                                          
runtime.mapassign1(0x5e3b40, 0xc08204c1e0, 0xc082119eac, 0xc082119ec0)                                                                                                
        C:/Go/src/runtime/hashmap.go:445 +0xb8 fp=0xc082119e68 sp=0xc082119dc0                                                                                        
main.(*Game).loadImages.func2(0xc08200a3c0, 0xc08200a3b0, 0x32, 0xc0820bc180)                                                                                         
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/go-inovation/main.go:459 +0x2f5 fp=0xc082119f80 sp=0xc082119e68                                            
runtime.goexit()                                                                                                                                                      
        C:/Go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc082119f88 sp=0xc082119f80                                                                                       
created by main.(*Game).loadImages                                                                                                                                    
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/go-inovation/main.go:460 +0x2df                                                                            

goroutine 1 [syscall, locked to thread]:                                                                                                                              
github.com/go-gl/glfw/v3.1/glfw._Cfunc_glfwShowWindow(0x1f7850)                                                                                                       
        ??:0 +0x3d                                                                                                                                                    
github.com/go-gl/glfw/v3.1/glfw.(*Window).Show(0xc0820be000)                                                                                                          
        C:/Users/hajimehoshi/go/src/github.com/go-gl/glfw/v3.1/glfw/window.go:412 +0x7f                                                                               
github.com/hajimehoshi/ebiten/internal/ui.(*UserInterface).Start(0xc0820c2000, 0x140, 0xf0, 0x2, 0x710200, 0x1b, 0x0, 0x0)                                            
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:133 +0x28b                                                                   
github.com/hajimehoshi/ebiten.Run(0xc082125ea0, 0x140, 0xf0, 0x2, 0x710200, 0x1b, 0x0, 0x0)                                                                           
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/run.go:170 +0xc6                                                                                    
main.(*Game).Start(0xc0820bc180, 0x0, 0x0)                                                                                                                            
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/go-inovation/main.go:283 +0x77                                                                             
main.Run(0x0, 0x0)                                                                                                                                                    
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/go-inovation/main.go:478 +0x197                                                                            
main.main()                                                                                                                                                           
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/go-inovation/main.go:482 +0x23                                                                             

goroutine 17 [syscall, locked to thread]:                                                                                                                             
runtime.goexit()                                                                                                                                                      
        C:/Go/src/runtime/asm_amd64.s:1998 +0x1                                                                                                                       

goroutine 18 [runnable, locked to thread]:                                                                                                                            
github.com/go-gl/gl/v2.1/gl._Cfunc_glowGenTextures(0x7ffc43898d40, 0xc000000001, 0xc08213e8e4)                                                                        
        github.com/go-gl/gl/v2.1/gl/_obj/_cgo_gotypes.go:14813 +0x41                                                                                                  
github.com/go-gl/gl/v2.1/gl.GenTextures(0x1, 0xc08213e8e4)                                                                                                            
        C:/Users/hajimehoshi/go/src/github.com/go-gl/gl/v2.1/gl/package.go:20002 +0x3c                                                                                
github.com/hajimehoshi/ebiten/internal/graphics/opengl.(*Context).NewTexture.func1()                                                                                  
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/graphics/opengl/context_desktop.go:135 +0x87                                               
github.com/hajimehoshi/ebiten/internal/graphics/opengl.(*Context).RunOnContextThread.func1()                                                                          
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/graphics/opengl/context_desktop.go:92 +0x2f                                                
github.com/hajimehoshi/ebiten/internal/graphics/opengl.(*Context).Loop(0xc0820ce000)                                                                                  
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/graphics/opengl/context_desktop.go:84 +0x66                                                
github.com/hajimehoshi/ebiten/internal/ui.Init.func1(0xc0820c2000, 0xc0820c4000)                                                                                      
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:79 +0xf9                                                                     
created by github.com/hajimehoshi/ebiten/internal/ui.Init                                                                                                             
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:80 +0x377                                                                    

goroutine 19 [semacquire]:                                                                                                                                            
sync.runtime_Semacquire(0xc08200a3cc)                                                                                                                                 
        C:/Go/src/runtime/sema.go:47 +0x2d                                                                                                                            
sync.(*WaitGroup).Wait(0xc08200a3c0)                                                                                                                                  
        C:/Go/src/sync/waitgroup.go:127 +0xbb                                                                                                                         
main.(*Game).loadImages(0xc0820bc180)                                                                                                                                 
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/go-inovation/main.go:462 +0x2fb                                                                            
main.Run.func1(0xc0820bc180)                                                                                                                                          
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/go-inovation/main.go:473 +0x28                                                                             
created by main.Run                                                                                                                                                   
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/go-inovation/main.go:474 +0x167                                                                            

goroutine 20 [syscall, locked to thread]:                                                                                                                             
github.com/hajimehoshi/ebiten/exp/audio._Cfunc_waveOutOpen2(0xc082136000, 0xc082134000, 0xc000000000)                                                                 
        ??:0 +0x48                                                                                                                                                    
github.com/hajimehoshi/ebiten/exp/audio.newPlayer(0x3060000, 0xc082128040, 0xac44, 0x3060000, 0x0, 0x0)                                                               
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/exp/audio/audio_windows.go:98 +0x22f                                                                
github.com/hajimehoshi/ebiten/exp/audio.NewContext(0xac44, 0xc08212a000, 0x0, 0x0)                                                                                    
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/exp/audio/audio.go:200 +0x175                                                                       
main.(*Game).loadAudio(0xc0820bc180)                                                                                                                                  
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/go-inovation/audio.go:33 +0x7f                                                                             
main.Run.func2(0xc0820bc180)                                                                                                                                          
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/go-inovation/main.go:476 +0x28                                                                             
created by main.Run                                                                                                                                                   
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/go-inovation/main.go:477 +0x189                                                                            

goroutine 6 [runnable]:                                                                                                                                               
io.ReadFull(0x30a00d8, 0xc082312050, 0xc0827d4900, 0x801, 0x801, 0x801, 0x0, 0x0)                                                                                     
        C:/Go/src/io/io.go:314                                                                                                                                        
image/png.(*decoder).readImagePass(0xc082348000, 0x30a00d8, 0xc082312050, 0x0, 0xc082312000, 0x0, 0x0, 0x0, 0x0)                                                      
        C:/Go/src/image/png/reader.go:445 +0x5a7                                                                                                                      
image/png.(*decoder).decode(0xc082348000, 0x0, 0x0, 0x0, 0x0)                                                                                                         
        C:/Go/src/image/png/reader.go:328 +0x1a8                                                                                                                      
image/png.(*decoder).parseIDAT(0xc082348000, 0xe7fa, 0x0, 0x0)                                                                                                        
        C:/Go/src/image/png/reader.go:673 +0x41                                                                                                                       
image/png.(*decoder).parseChunk(0xc082348000, 0x0, 0x0)                                                                                                               
        C:/Go/src/image/png/reader.go:722 +0x410                                                                                                                      
image/png.Decode(0x2db4380, 0xc0821d2060, 0x0, 0x0, 0x0, 0x0)                                                                                                         
        C:/Go/src/image/png/reader.go:781 +0x218                                                                                                                      
image.Decode(0x2db42f8, 0xc0821cc000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)                                                                                                   
        C:/Go/src/image/format.go:84 +0x208                                                                                                                           
github.com/hajimehoshi/ebiten/ebitenutil.NewImageFromFile(0xc08219e020, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)                                                           
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/ebitenutil/loadimage.go:33 +0x13b                                                                   
main.(*Game).loadImages.func1(0xc08200a3c0, 0xc08200a3b0, 0x6b9180, 0x3, 0xc0820bc180)                                                                                
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/go-inovation/main.go:440 +0x1e9                                                                            
created by main.(*Game).loadImages                                                                                                                                    
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/go-inovation/main.go:441 +0x1be                                                                            

goroutine 7 [chan receive]:                                                                                                                                           
github.com/hajimehoshi/ebiten/internal/graphics/opengl.(*Context).RunOnContextThread(0xc0820ce000, 0xc08216c320)                                                      
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/graphics/opengl/context_desktop.go:95 +0xea                                                
github.com/hajimehoshi/ebiten/internal/graphics/opengl.(*Context).NewTexture(0xc0820ce000, 0x200, 0x400, 0xc082806000, 0x200000, 0x200000, 0x2600, 0x0, 0x0, 0x0)     
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/graphics/opengl/context_desktop.go:155 +0x104                                              
github.com/hajimehoshi/ebiten/internal/graphics.NewTextureFromImage(0xc0820ce000, 0x30a0178, 0xc08213c140, 0x2600, 0xc08216e000, 0x0, 0x0)                            
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/graphics/texture.go:82 +0x3c5                                                              
github.com/hajimehoshi/ebiten.NewImageFromImage(0x30a0178, 0xc08213c140, 0x0, 0xc08213c140, 0x0, 0x0)                                                                 
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/image.go:228 +0x81                                                                                  
github.com/hajimehoshi/ebiten/ebitenutil.NewImageFromFile(0xc082158020, 0x1b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)                                                           
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/ebitenutil/loadimage.go:37 +0x1bd                                                                   
main.(*Game).loadImages.func1(0xc08200a3c0, 0xc08200a3b0, 0x6b8458, 0x2, 0xc0820bc180)                                                                                
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/go-inovation/main.go:440 +0x1e9                                                                            
created by main.(*Game).loadImages                                                                                                                                    
        C:/Users/hajimehoshi/go/src/github.com/hajimehoshi/go-inovation/main.go:441 +0x1be                                                                            
exit status 2                                                                                                                                                         
exit status 1                                                                                                                                                         
```

**Comment by hajimehoshi** [comment]
Ah, loading process like loadImages() manipulates a map concurrently.
